### PR TITLE
To do list project

### PR DESCRIPTION
**Pull request by zunairkhan811**
In this project a user can add and remove his daily task lists and as well as edit it.
This project is completed and pull requested is ready for review to check if there are any issues related to:
- DRY, KISS and YAGNI
- Javascript best practice
- HTML and CSS best practice

### CODE REVIEW

**Comment by prius2055** [comment]
Hello Khan, Your project looks very good and working perfectly. But you will need to take a few steps following best practices.
I will like you to take note of the following points.

- Always use words for iterables like forEach, map etc. Avoid using just letters:
https://github.com/zunairkhan811/To-do-list-Review-Excercise/blob/ed9feff1868f1b38ed02b55b6f42cc1d804e001a/modules/clearbutton.js#L7-L9

https://github.com/zunairkhan811/To-do-list-Review-Excercise/blob/ed9feff1868f1b38ed02b55b6f42cc1d804e001a/modules/interative.js#L8-L9

- Avoid the use of negative conditionals in your code blocks
https://github.com/zunairkhan811/To-do-list-Review-Excercise/blob/ed9feff1868f1b38ed02b55b6f42cc1d804e001a/src/index.js#L10-L12

https://github.com/zunairkhan811/To-do-list-Review-Excercise/blob/ed9feff1868f1b38ed02b55b6f42cc1d804e001a/src/index.js#L50

**Comment by zunairkhan811** [comment]
Hi! thanks for your suggestion 😉  I have implemented the changes asked by you but the reason I used the negational condition Is because i want to keep it simple and shorter code according to the KISS principle that is why i haven't removed negational condition in order to keep my code shorter and simple. But other than that  i have implemented the changes . 😍

**Comment by prius2055** [comment]
**Nice work Khan 👍 ,** 

Your project is perfect 💯  and ready to be merged. You can go ahead and merge.

**Review by prius2055 — APPROVED** [review]
**Nice work @zunairkhan811** 

Your project is perfect, no errors were found. You go ahead and merge.

Congratulations 💯

**Pull request merged**
